apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-haven
spec:
  rules:
    - host: haven.epicbugs.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: haven
                port:
                  number: 3000
  ingressClassName: nginx